// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PageFilterSortApp.Data.Context;

namespace PageFilterSortApp.Data.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20220925173136_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PageFilterSortApp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("MarriageStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalOrderCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 26,
                            Firstname = "Semih",
                            Gender = "Male",
                            Lastname = "Ilgaz",
                            MarriageStatus = "Single",
                            TotalOrderCount = 28
                        },
                        new
                        {
                            Id = 2,
                            Age = 19,
                            Firstname = "Kerem",
                            Gender = "Male",
                            Lastname = "Erdogdu",
                            MarriageStatus = "Single",
                            TotalOrderCount = 58
                        },
                        new
                        {
                            Id = 3,
                            Age = 43,
                            Firstname = "Ali",
                            Gender = "Male",
                            Lastname = "Cakir",
                            MarriageStatus = "Married",
                            TotalOrderCount = 12
                        },
                        new
                        {
                            Id = 4,
                            Age = 23,
                            Firstname = "Ebru",
                            Gender = "Female",
                            Lastname = "Deniz",
                            MarriageStatus = "Single",
                            TotalOrderCount = 8
                        },
                        new
                        {
                            Id = 5,
                            Age = 34,
                            Firstname = "Sinem",
                            Gender = "Female",
                            Lastname = "Yılmaz",
                            MarriageStatus = "Married",
                            TotalOrderCount = 41
                        },
                        new
                        {
                            Id = 6,
                            Age = 28,
                            Firstname = "Ceyhan",
                            Gender = "Female",
                            Lastname = "Korkmaz",
                            MarriageStatus = "Single",
                            TotalOrderCount = 6
                        },
                        new
                        {
                            Id = 7,
                            Age = 47,
                            Firstname = "Berkcan",
                            Gender = "Male",
                            Lastname = "Hasanoglu",
                            MarriageStatus = "Single",
                            TotalOrderCount = 126
                        },
                        new
                        {
                            Id = 8,
                            Age = 19,
                            Firstname = "Onur",
                            Gender = "Male",
                            Lastname = "Aslan",
                            MarriageStatus = "Single",
                            TotalOrderCount = 17
                        },
                        new
                        {
                            Id = 9,
                            Age = 35,
                            Firstname = "Suleyman",
                            Gender = "Male",
                            Lastname = "Demir",
                            MarriageStatus = "Single",
                            TotalOrderCount = 32
                        },
                        new
                        {
                            Id = 10,
                            Age = 28,
                            Firstname = "Kaan",
                            Gender = "Male",
                            Lastname = "Avci",
                            MarriageStatus = "Married",
                            TotalOrderCount = 205
                        },
                        new
                        {
                            Id = 11,
                            Age = 58,
                            Firstname = "Engin",
                            Gender = "Male",
                            Lastname = "Yurtgezer",
                            MarriageStatus = "Single",
                            TotalOrderCount = 41
                        },
                        new
                        {
                            Id = 12,
                            Age = 25,
                            Firstname = "Selin",
                            Gender = "Female",
                            Lastname = "Uzuner",
                            MarriageStatus = "Single",
                            TotalOrderCount = 16
                        },
                        new
                        {
                            Id = 13,
                            Age = 32,
                            Firstname = "Seyma",
                            Gender = "Female",
                            Lastname = "Sezengil",
                            MarriageStatus = "Married",
                            TotalOrderCount = 83
                        },
                        new
                        {
                            Id = 14,
                            Age = 33,
                            Firstname = "Orhan",
                            Gender = "Male",
                            Lastname = "Sabuncu",
                            MarriageStatus = "Single",
                            TotalOrderCount = 41
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
